name: setup
description: standard job setup
runs:
  using: "composite"
  steps:
    - name: Configure direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - name: checkout
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '.nvmrc'
        cache: 'yarn'

    - name: Install Dependencies
      shell: bash
      run: yarn install:all