services:
  alerts:
    path: src/services/alerts
  appian:
    path: src/services/appian
  seatool:
    path: src/services/seatool
  compare-appian:
    dependsOn:
      - alerts
      - appian
      - seatool
    path: src/services/compare-appian
    params:
      appianTableArn: ${appian.TableArn}
      appianTableName: ${appian.TableName}
      appianTableStreamArn: ${appian.TableStreamArn}
      seatoolTableName: ${seatool.TableName}
      seatoolTableArn: ${seatool.TableArn}
      sesLogGroupArn: ${alerts.SesLogGroupArn}
      sesLogGroupName: ${alerts.SesLogGroupName}
      errorsTopicArn: ${alerts.ErrorsTopicArn}
  connector:
    dependsOn:
      - alerts
      - compare-appian
      - appian
      - seatool
    path: src/services/connector
    params:
      appianTableArn: ${appian.TableArn}
      appianTableName: ${appian.TableName}
      seatoolTableName: ${seatool.TableName}
      seatoolTableArn: ${seatool.TableArn}
      alarmsTopicArn: ${alerts.AlarmsTopicArn}
